.TH MYSTRLEN 3 "September 2025" "libmyutils" "Library Functions"
.SH NAME
mystrlen \- return length of a C string
.SH SYNOPSIS
.B int mystrlen(const char *s);
.SH DESCRIPTION
mystrlen computes the number of characters in the null-terminated string s,
not including the terminating null byte. Returns 0 if s is NULL.
.SH AUTHOR
Rameesha Shakeel <rameesha@example.com>
